CMS/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#index"
  resources :pages, :users
  mount Ckeditor::Engine => '/ckeditor'
  get '/blog', to: 'pages#blog'
  get '/users/:id/upgrade', to: 'users#upgrade', as: :upgrade
  get '/users/:id/downrade', to: 'users#downgrade', as: :downgrade
end

CMS/app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

CMS/app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

CMS/app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

CMS/app/models/page.rb
class Page < ActiveRecord::Base
  validates :title, :user_id, presence: true

  belongs_to :user

  scope :sorted, -> { Page.includes(:user).order(index: :asc) }
end

CMS/app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :rememberable, :trackable, :validatable

  has_many :pages, dependent: :destroy

  validates :full_name, presence: true
end

CMS/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  include Authorization

  protect_from_forgery with: :exception

  responders :flash
  respond_to :html

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end
end

CMS/app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    helper do
      def current_user
        super.decorate if user_signed_in?
      end
    end
  end

  private

  def devise_parameter_sanitizer
    if resource_class == User
      User::ParameterSanitizer.new(User, :user, params)
    else
      super
    end
  end
end

CMS/app/controllers/concerns/authorization.rb
module Authorization
  extend ActiveSupport::Concern

  included do
    include Pundit
    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  end

  private

  def user_not_authorized
    redirect_to(root_path)
  end
end

CMS/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, except: [:blog, :show]

  respond_to :html

  expose_decorated(:page, attributes: :page_params)
  expose(:policy) { PagePolicy.new(current_user, page) }

  def index
    @pages = Page.sorted.decorate
  end

  def show
    page = Page.find_by_url(params[:id]) || Page.find(params[:id])
    @page = page.decorate 
  end

  def new
  end

  def blog
    @pages = Page.includes(:user).where(static: false).decorate 
  end

  def create
    page.user = current_user

    flash[:notice] = "Page was successfully created." if page.save
    respond_with page, location: pages_path
  end

  def update
    if policy.edit?
      flash[:notice] = "Page was successfully updated." if page.save
      respond_with page, location: pages_path
    end
  end

  def destroy
    if policy.destroy?
      page.destroy
      respond_with page, location: pages_path
    end
  end

  def edit
    unless policy.edit?
      redirect_to pages_path
    end
  end

  private

  def page_params
    params.require(:page).permit(:user_id, 
                                 :title,
                                 :content,
                                 :index, 
                                 :url,
                                 :static)
  end
end

CMS/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action do
    redirect_to root_path unless policy.manage?
  end

  respond_to :html

  expose(:policy) { UserPolicy.new(current_user) }

  def index
    all = User.all.decorate
    @admins = all.select { |u| u.admin? }
    @users = all.reject { |u| u.admin? }
  end

  def downgrade
    change_role_to 'user'
  end

  def upgrade
    change_role_to 'administrator'
  end

  private

  def change_role_to x
    user = User.find(params[:id])
    user.role = x
    user.save
    redirect_to users_path
  end

end

CMS/app/views/application/_messages.html.slim
	- flash.each do |type, content|
		.row
  			.medium-8.medium-centered.columns
				  div(data-alert class="alert-box #{type}" tabindex="0" aria-live="assertive" role="alertdialog")
				    = content
				    button.close(tabindex="0" aria-label="Close Alert") &times;

CMS/app/views/application/_navigation.html.slim
.row
  .small-12.large-expand.columns
      = render "navigation_user"
      = link_to "Content Management System", root_path, class: 'success button', id: 'logo'
      = link_to 'Blog Articles', '/blog', class: 'button'

= render "navigation_main"

CMS/app/views/application/_navigation_main.html.slim
.left.panel.callout(style='width:200px')
		- Page.where(static: true).order(index: :asc).each do |page|
		    = link_to page.title, page
		    br

CMS/app/views/application/_navigation_user.html.slim
.right
  - if user_signed_in?
      a.button.secondary.dropdown(href="#", data-dropdown="drop1") = current_user.full_name
      ul.f-dropdown#drop1(data-dropdown-content)

        li= current_user.admin? ? link_to('Edit user roles', users_path) : ''

        li
          a href = edit_user_registration_path
            | Edit my profile
        li
          a href = destroy_user_session_path
            | Sign out
  - else
    = link_to "Login", new_user_session_path, class: 'secondary button'
    = link_to "Register", new_user_registration_path, class: 'secondary button'

CMS/app/views/layouts/application.html.slim
doctype html

html class="no-js" lang="en"

  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    meta name="robots" content="NOODP,NOYDIR"

    = metamagic site: "CMS", title: %i(title site), separator: " - "
    = csrf_meta_tags

    = stylesheet_link_tag :application

    = javascript_include_tag "vendor/modernizr"

    = javascript_tag "window.App = {}"

    == analytics_init if GA.tracker

  body
      = render "navigation"
      = render "messages"
      
      .row#content
        = yield

      javascript:
        App.currentUserData = #{{current_user.to_json}};

      = javascript_include_tag :application

CMS/app/views/pages/_form.html.slim
.scaffold-form
  = simple_form_for page do |form|
    .form-inputs
      = form.input :title
      = form.cktext_area :content, :class => 'Page', :ckeditor => {:language => 'uk'}
      = form.input :index
      = form.input :url
      = form.collection_radio_buttons :static, [[true, 'Static page'], [false, 'News article']], :first, :last

    .form-actions
      = form.button :submit
      '  or
      = link_to 'Back', :back

CMS/app/views/pages/_page.html.slim
.panel.radius
  	h3= link_to(page) do
  		= page.title
  	= page.content.html_safe
    .label.right
    	| Created by 
    	= page.author

CMS/app/views/pages/blog.html.slim
.row
  .medium-8.medium-centered.columns
  	- @pages.each do |page|
  		= render page

CMS/app/views/pages/edit.html.slim
.row
  .medium-8.medium-centered.columns
    h2 Edit page
    = render 'form'

CMS/app/views/pages/home.html.slim
.row
  .columns
    h2
      = title("Home")

CMS/app/views/pages/index.html.slim
.row
  .medium-8.medium-centered.columns
    h2 Pages
    table.table.table-striped.pages-list
      thead
        tr
            th Author
            th Title
            th Type
            th Index
            th Custom URL
            th Available Actions
      - @pages.each do |page|
        - policy = PagePolicy.new(current_user, page)
        tr
          td= page.author
          td
            = link_to(page) do
              = page.title

          td= page.static ? 'Static' : 'Article'

          td= page.index
          td
            = link_to('pages/' + page.url) do
              = page.url
          td
            - if policy.edit?
              = link_to(edit_page_path(page)) do
                  | Edit 
            | - 
            - if policy.destroy?
              = link_to(page, method: :delete, data: { confirm: 'Are you sure?' }) do
                  | Remove

    br
    = link_to new_page_path, class: 'button' do
      i.fi-plus
      |  New Page

CMS/app/views/pages/new.html.slim
.row
  .medium-8.medium-centered.columns
    h2 Create new page
    = render 'form'

CMS/app/views/pages/show.html.slim
.row
  .medium-8.medium-centered.columns
	= render @page

CMS/app/views/users/index.html.slim
.row
  .medium-8.medium-centered.columns
    br
    h4 Editors
    table.table.table-striped.pages-list
      thead
        tr
            th User
            th Actions
      - @admins.each do |user|
        tr
          td= user.full_name_with_email
          td= link_to 'Remove from editors', downgrade_path(user.id)

    h4 Users
    table.table.table-striped.pages-list
      thead
        tr
            th User
            th Actions
      - @users.each do |user|
        tr
          td= user.full_name_with_email
          td= link_to 'Make editor', upgrade_path(user.id)

CMS/app/views/users/shared/_links.html.slim
h6 Anything else?
ul.links
  - if controller_name != "sessions"
    li = link_to "Sign in", new_session_path(resource_name)

  - if devise_mapping.registerable? && controller_name != "registrations"
    li = link_to "Create a new account", new_registration_path(resource_name)

  - if devise_mapping.recoverable? && controller_name != "passwords"
    li = link_to "Forgot your password?", new_password_path(resource_name)

  - if devise_mapping.confirmable? && controller_name != "confirmations"
    li = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)

  - if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != "unlocks"
    li = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)

  - if devise_mapping.omniauthable?
    - resource_class.omniauth_providers.each do |provider|
      li = link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider)