blog/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :articles do
    resources :comments
  end

  root 'articles#index'

end

blog/app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
  validates :text, presence: true,
                    length: { minimum: 10 }
end

blog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  validates :commenter, presence: true,
                    length: { minimum: 3 }
  validates :body, presence: true
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all.reverse
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
  	@article = Article.new
  end

  def create
    @article = Article.new(article_params)
 
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end
 
  private
  def article_params
    params.require(:article).permit(:title, :text)
  end
end

blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog/app/helpers/comments_helper.rb
module CommentsHelper
end

blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

blog/app/views/articles/_article.html.erb
<div class="row">
    <div class="col-sm-8 blog-main">
      <div class="blog-post">
        <h2 class="blog-post-title"><%= link_to article.title, article_path(article) %></h2>
        <p class="blog-post-meta">Comments: <%= article.comments.count %> </p>
        <%= article.text %>
      </div>
    </div>
</div>

blog/app/views/articles/index.html.erb
<% @articles.each do |article| %>
  <%= render 'article', :article => article %>
<% end %>

blog/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_for :article, url: articles_path do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class='well'>

  <div class="input-group">
    <span class="input-group-addon" id="title"><%= f.label :title %></span>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <br>
  <p>
    <%= f.text_area :text, class: 'form-control', rows: "10" %>
  </p>
 
  <p>
    <%= f.submit 'Save', class: 'btn btn-default btn-lg' %>
  </p>
</div>
<% end %>

blog/app/views/articles/show.html.erb
<%= render 'article', :article => @article %>

<div class="well well-lg">
	<h4><%= @article.comments.empty? ? '' : 'Comments' %></h4>
	
	<%= render @article.comments %>

	<h4>Add a comment:</h4>
	<%= render 'comments/form' %>
</div>

blog/app/views/comments/_comment.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= comment.commenter %>:</h3>
  </div>
  <div class="panel-body">
    <%= comment.body %>
  </div>
</div>

blog/app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
<div class="input-group">
    <span class="input-group-addon" id="title">Name</span>
    <%= f.text_field :commenter, class: 'form-control' %>
  </div>
  <br>
  <p>
    <%= f.text_area :body, class: 'form-control', rows: "5" %>
  </p>
  <p>
    <%= f.submit 'Send', class: 'btn btn-default btn-lg' %>
  </p>
<% end %>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yet another blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav">
        	<%= link_to 'All posts', articles_path, class: 'blog-nav-item' %>
			<%= link_to 'New article', new_article_path, class: 'blog-nav-item' %>
        </nav>
      </div>
    </div>

    <div class="container">

      <div class="blog-header">
        <h1 class="blog-title">Yet Another Blog</h1>
        <p class="lead blog-description"> by Rinat Khanov.</p>
      </div>

	<%= yield %>

    </div>

</body>
</html>

blog/app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>